### ISSUE TITLE
Potential update in definition of damping

### ISSUE THREAD

**Issue by gauravharsha** [Green-Phys/green-sc#4]
In the Green framework, the definition of damping is such that
```
obj_n = obj_n * damping + obj_n_1 * (1 - damping)
```
where `obj_n` is the result for current iteration, and `obj_n_1` is the result for previous iteration.
So, `damping=1` would result in no damping in our codes.

However, in PySCF and other quantum chemistry packages, the definition is the opposite, i.e., `damping=0` results in no damping.

Question to everyone: should we keep our definition consistent with that in PySCF, the software package we use to prepare our input?

**Comment by pavel-po** [comment]
No, no, no. The definition that we have in the code now is the one that is the most consistent with DIIS. Please don't redefine it because it will break a lot of calculations the users already have.

The definition that is present now is also consistent with the definition from the old code that we have locally.

**Comment by gauravharsha** [comment]
It is understandable that this change will be incompatible with previous calculations, and also require some editing of DIIS parts. This is why I am posing it as a question, and not a bug or feature request.

The way I see it, we have had some major changes in the structure of the code already, and we are still in the BETA version. So, if we desire to make these definitions consistent, now is the opportunity.

**Comment by pavel-po** [comment]
The claim about consistency with the older versions is definitely false for the last two years. I am strongly against such changes because they don't serve any real benefit and cause a giant headache for those actually working with the code already.

**Comment by gauravharsha** [comment]
This is exactly my point. The current users, specially those familiar with other q. chem. codes, had to go through the confusion between different damping defs. For new users, maybe this will make life relatively easier, though at the expense of further headache for us.

Once again, I am neither "for" nor "against" this change. I noticed this behavior and thought it is something that needs a little attention from developers.

**Comment by pavel-po** [comment]
My point is actually in maintaining consistency with the Green's function codes rather then with other more distant codes. Such things should be defined once and carefully described. I would argue that most users do not appreciate when the definition of the parameter changes from version to version. So I am against the change.

**Comment by gauravharsha** [comment]
1. PySCF isn't that distant. We are using it for zeroth step, way before we can run the GW or GF2 calcs.
2. Technically, we are yet to have a FULL RELEASE of the green-phys software. This is why I say, **should we decide to update the definition, now is the only chance**. Once again, I am not saying we should or shouldn't make this change.

**Comment by iskakoff** [comment]
After several discussion, the final decision is:
   - rename `damping` to `mixing_weight`
   - introduce "new" `damping` parameter that has no default values and code will throw an exception if the value is provided

The reason for damping to be `x_n = (1-a) x_n + a x_{n-1}` comes from the definition of such term in dictionary, and we obviously used it wrong. It is right time to rename it and avoid any possible confusion in the future.

The proposed changes are in the PR #5 please review it and I will close this issue.

**Comment by iskakoff** [comment]
Closed PR #5
